# config file version
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-metrics
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpMethod: GET
      execmplarTraceIdDestinations:
        - datasourceUid: jaeger-traces
          name: trace_id

        - url: http://localhost:8080/jaeger/ui/trace/$${_value.raw}
          name: trace_id
          urlDisplayLabel: View in Jaeger UI

  - name: Jaeger
    uid: jaeger-traces
    type: jaeger
    url: http://jaeger:16686
    editable: true
    isDefault: false

  - name: loki
    type: loki
    uid: loki-logs
    url: http://loki:3100
    editable: true
    isDefault: false
